#!/bin/sh

git submodule update --init .zsh .vim z

for f in .profile .shrc .bashrc .inputrc .zshrc .tmux.conf .screenrc .vim .vim/.vimrc .calendar .emacs.d; do
  fn=$(basename $f)
  fl=$(readlink -f ~/$fn)
  [ "$fl" = "$(pwd)/$f" ] || [ ! -r "$f" ] || {
    echo symlinking $f 
    [ -e ~/$fn -o -h ~/$fn ] && mv ~/$fn ~/$fn.$(date +%Y%m%d%H%M%S)
    ln -s $(pwd)/$f ~/$fn
  }
done

mkdir -p ~/bin
[ -r ~/bin/z.sh ] || ln -s $PWD/z/z.sh ~/bin/z.sh

case $1 in
--full)
        git submodule update --init --recursive
        cd .emacs.d/vendor/pymacs
        make && python setup.py install --user
        ;;
*)
        echo "run install --full for emacs setup"
        ;;
esac


