#!/usr/bin/env zsh

git submodule init
# if the main repo is cloned from read-only url rewrite submodule urls as read only
if grep "git://github.com/alexko" .git/config; then
  sed -i 's/git@github.com:alexko/git:\/\/github.com\/alexko/' .git/config
fi
if grep "https://github.com/alexko" .git/config; then
  sed -i 's/git@github.com:alexko/https:\/\/github.com\/alexko/' .git/config
fi  
git submodule update

for f in .zshrc .screenrc .emacs.d .vim .vim/.vimrc
do
  [ ~/$f -ef $(pwd)/$f ] || {
    echo symlinking $f 
    [ -e ~/$f:t ] && mv ~/$f:t ~/$f:t.$(date +%Y%m%d%H%M%S)
    ln -s $(pwd)/$f ~/$f:t
  }
done
