#!/usr/bin/env zsh

git submodule update --init .zsh .vim

for f in .zshrc .screenrc .vim .vim/.vimrc .calendar .emacs.d
do
  [ ~/$f:t -ef $(pwd)/$f ] || {
    echo symlinking $f 
    [ -e ~/$f:t -o -h ~/$f:t ] && mv ~/$f:t ~/$f:t.$(date +%Y%m%d%H%M%S)
    ln -s $(pwd)/$f ~/$f:t
  }
done

mkdir -p ~/bin
[ -r ~/bin/z.sh ] || ln -s $PWD/z/z.sh ~/bin/z.sh

case $1 in
--full)
        git submodule update --init --recursive
        cd .emacs.d/vendor/pymacs
        make && python setup.py install --user
        ;;
*)
        echo "run install --full for emacs setup"
        ;;
esac


